language: python

python:
  - "2.6"
  - "2.7"
  - "3.0"
  - "3.1"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install python-wxgtk2.8 python-wxtools wx2.8-i18n
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install ."
  - "python setup.py install"
# command to run tests
script: python tests/test_main.py
