language: python

python:
  - "2.6"
  - "2.7"

# command to install dependencies
before_install:
  - sudo apt-get update -qq
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install ."
  - "python setup.py install"
# command to run tests
script: python tests/test_main.py photo
