language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
# command to install dependencies
install:
  - "apt-get install python-wxgtk2.9"
  - "pip install -r requirements.txt"
  - "python setup.py install"
# command to run tests
script: python start_ui.py
