language: python

python:
  - "2.6"
  - "2.7"

# command to install dependencies
before_install:
  - sudo apt-get update -qq
  - wget http://downloads.sourceforge.net/wxpython/wxPython-src-3.0.1.1.tar.bz2
  - tar -xf wxPython-src-3.0.1.1.tar.bz2
  - cd wxPython-src-3.0.1.1
  - python setup.py build
  - sudo python setup.py install
  - cd ..
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "python setup.py install"
# command to run tests
script: python start_ui.py
