language: python

python:
  - "2.7"
# command to install dependencies
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install python-wxgtk2.8 python-wxtools wx2.8-i18n
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install ."
  - "python setup.py install"
# command to run tests
script: python tests/test_main.py
