language: python

python:
  - "2.7"
# command to install dependencies
before_install:
  - sudo apt-get update -qq
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "apt-get install python-wxgtk3.0 python-wxtools wx3.0-i18n"
  - "pip install ."
  - "python setup.py install"
# command to run tests
script: python tests/test_main.py photo
