language: python

python:
  - "2.6"
  - "2.7"

# command to install dependencies
before_install:
  - sudo apt-get update -qq
  - wget http://sourceforge.net/projects/wxpython/files/wxPython/2.9.4.0/wxPython-src-2.9.4.0.tar.bz2
  - tar jxvf wxPython-src-2.9.4.0.tar.bz2
  - cd wxPython-src-2.9.4.0/
  - wget http://sourceforge.net/projects/wxpython/files/wxPython/2.9.4.0/wxPython-src-2.9.4.1.patch
  - patch -p0 < wxPython-src-2.9.4.1.patch
  - cd wxPython/
  - python build-wxpython.py --build_dir=../bld
  - cd ..
  - export PYTHONPATH="$PWD/wxPython"
  - export LD_LIBRARY_PATH="$PWD/bld/lib"
  - cd ..
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "python setup.py install"
# command to run tests
script: python start_ui.py
