language: python
python:
  - "2.6"
  - "2.7"

# command to install dependencies
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-wxgtk2.8
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "python setup.py install"
# command to run tests
script: python start_ui.py
